from entailmentClassifier import findEntailmentClassificationOfEachEvidence
from votingClassifier import votingClassifier


def classificationLayer(entailmentClassifierTokenizer, entailmentClassifierModel, inputClaim, preprocessedEvidences):
  entailmentClassificationOfEachEvidence = findEntailmentClassificationOfEachEvidence(entailmentClassifierTokenizer, entailmentClassifierModel, inputClaim, preprocessedEvidences)
  votingClassifierPrediction = votingClassifier(entailmentClassificationOfEachEvidence)

  return votingClassifierPrediction
